### ISSUE TITLE
Chat gpt 中文

### ISSUE THREAD

**Issue by au99822555** [PlexPt/awesome-chatgpt-prompts-zh#123]

**Comment by mengxianng** [comment]
润色以下文字：The theory of the medicinal properties of Mongolian medicines is an important basis for guiding clinical prescriptions, with hot and cold medicinal properties as its core. The use of "bashaga" has a long history, but there is still no objective basis for scientific analysis of its medicinal properties. To explore the establishment of a method for evaluating the hot and cold properties of Mongolian medicines and to explain their theoretical and scientific connotations is an urgent problem to be solved. The group has found that different components of the herb have different effects on the enzyme indexes and intestinal flora of rats with febrile diseases, and the current study has confirmed that the intestinal flora is closely related to material and energy metabolism. Therefore, it is proposed that the medicinal effects of Curetoxin and its fractions can be exerted through the regulation of "intestinal microorganisms - endogenous metabolites - material-energy metabolism". In this study, under the guidance of the pharmacological theory of Mongolian medicine, a combined metabolomic approach of intestinal flora was applied to investigate the effects of "Bashaga" type of Mongolian herbs on the basal and material-energy metabolism-related enzymes of normal rats, and to investigate the relationship between "intestinal microorganisms - endogenous biomarkers - material-energy metabolism". -The method was used to evaluate the medicinal properties and material basis of "Bashaga" herbal medicines from macroscopic to microscopic, and from local to overall. The method will be used to evaluate the medicinal properties and material basis of "Bashaga", reveal the mechanism of medicinal properties, and provide an experimental basis for the rational clinical application and development of "Bashaga" and further improve the theoretical study of the medicinal properties of Mongolian medicines.
