### ISSUE TITLE
到底该如何导入json文件

### ISSUE THREAD

**Issue by tianhuahao** [PlexPt/awesome-chatgpt-prompts-zh#132]
我尝试了输入json文件

```
{
    "type": "input",
    "name": "username",
    "message": "请输入您的用户名："
}
```
![image](https://user-images.githubusercontent.com/102142500/232305875-fdec1bf1-b3d4-4359-ab3c-a8a82283dc37.png)
点击导入后显示
JSON格式错误，请修正格式
![image](https://user-images.githubusercontent.com/102142500/232306183-5cac0c71-d1c2-47b1-a174-7238f3deb386.png)
这该怎么办

**Comment by tianhuahao** [comment]
导入成功后清空按钮不见了怎么办

**Comment by PlexPt** [comment]
请到对应项目下提问
