### ISSUE TITLE
javaScript怎么调用json啊

### ISSUE THREAD

**Issue by hdyyds666** [PlexPt/awesome-chatgpt-prompts-zh#137]
我不太会javaScript,
我想写一个下拉列表和一个表单，当选中下拉列表的option时，把json中的prompt填入表单中。
和gpt聊好几天了，每次的代码都不行，求大佬帮助

**Comment by PlexPt** [comment]
问CHATGPT

**Comment by hdyyds666** [comment]
和CHATGPT聊好几天了，我快死了
