### ISSUE TITLE
OpenAI ChatGPT 免费 账号汇总（经测试全部可用）

### ISSUE THREAD

**Issue by NianBroken** [PlexPt/awesome-chatgpt-prompts-zh#144]
pg99me0b@optm.cn        cudj0f7po!Bi
b2m7h888@optm.cn        d21oi8a@Tbw5
9uyo3rzl@optm.cn         ithsRr!2szn7
np9zqnbj@optm.cn        8gf7d!kK6plp
yncagm3z@optm.cn        xjtp6.0418Lc
0fd8mne4@optm.cn        sNi0yf5n@nue
naz6d781@optm.cn        o@Ciypdwbty0
ofy1oo3k@optm.cn        vC1co2wm!osu

其中有些账号是还有Key余额的，可自行前往https://platform.openai.com/account/api-keys获取密钥。

**Comment by reliedema** [comment]
你这全部都进不去
