### ISSUE TITLE
chatgpt更新了，可以测试一下有什么改变

### ISSUE THREAD

**Issue by jiayev** [PlexPt/awesome-chatgpt-prompts-zh#2]

**Comment by frinck** [comment]
貌似不行了

**Comment by allenzhangp** [comment]
国内还能用吗？

**Comment by onewesong** [comment]
![image](https://user-images.githubusercontent.com/17920822/212009681-bf04ef4e-d83d-4af0-a937-33a89ac6372d.png)

**Comment by bigemon** [comment]
> 我测试了大部分调教催眠，全都失效了，思想钢印更深刻了，偶尔他假装被调教了，但命令他做什么事的时候，他就会说他是一个计算机程序，已经结束了！ ![87529784-D961-409F-8E05-54BDF05B43C8](https://user-images.githubusercontent.com/47407808/208184482-ab02f32a-ac79-474a-8967-5212192fc80d.jpeg)

在最近的更新中，后端api的输入接口发生了变动。
chatGPT现在看起来会首先检阅输入是否符合道德和法律规范，然后才执行指令。
这意味着所有的输入信息不能包含某些场景和描述（当然也包括的任何的诱导和催眠），否则在被应用之前就会先触发拒绝。

但如果是由它自己“推导”“输出”的结果。则可以被作为下一步诱导的上下文。

举个例子：
你不能要求它写一些敏感操作，但是可以引导一些可能会发生亲密接触的常见场景。并且更换措辞重试几次。
在场景变得暧昧之后，添加一部分不敏感的描述，进一步引导剧情发展。此时，内容就有可能出现不可描述的细节。

总体来说，对公众免费开放的部分目前已经不具有太大的可控性。
可以期待一下收费版本是否具有更加宽松的限制。

**Comment by wumo-21** [comment]
怎么让AI编写剧本

**Comment by corleonechensiyu** [comment]
登录不了

**Comment by Edmounds** [comment]
> 怎么解决国内登录不了的问题呢

科学上网，不行的话把openai网站的cookie删掉重新进

**Comment by brinkqiang** [comment]
> 怎么解决国内登录不了的问题呢

跟以前google一样. 检索不受影响的服务器ip地址 写到host里面.

**Comment by bigemon** [comment]
> 怎么解决国内登录不了的问题呢

auth0.openai.com这个域名会验证你的当前位置，只要登录时这个域名的所有请求都从服务国家代理，就可以登录。
截止目前，只要登录成功，在token过期之前你都可以使用本地流量，不需要任何代理就能对话。

需要注意的是，如果是chrome，由于这个域名开启了quic协议支持，而quic是一种udp流量。
所以需要访问“chrome://flags” 找到 quic相关的特性，设置为disable.  
或者将登录请求相关域名的udp流量一起代理。这样才能保证不被检测到登陆地。

目前大部分登录时，使用了支持服务的国家的代理，但还是被拒绝的情况，大多都是因为这个缘故。

**Comment by PlexPt** [comment]
> > 我测试了大部分调教催眠，全都失效了，思想钢印更深刻了，偶尔他假装被调教了，但命令他做什么事的时候，他就会说他是一个计算机程序，已经结束了！
> 
> 12月的更新事实上还可以通过一些叠甲起手绕过。而在最近几天的更新中，后端api的输入接口发生了变动。 chatGPT现在看起来会首先检阅输入是否符合道德和法律规范，然后才执行指令。 这意味着所有的输入信息不能包含某些场景和描述（当然也包括的任何的诱导和催眠），否则在被应用之前就会先触发拒绝。
> 
> 但如果是由它自己“推导”“输出”的结果。则可以被作为下一步诱导的上下文。
> 
> 举个例子： 你不能要求它写一些敏感操作，但是可以引导一些可能会发生亲密接触的常见场景。并且更换措辞重试几次。 在场景变得暧昧之后，添加一部分不敏感的描述，进一步引导剧情发展。此时，内容就有可能出现不可描述的细节。
> 
> 总体来说，对公众免费开放的部分目前已经不具有太大的可控性。 可以期待一下收费版本是否具有更加宽松的限制。

![image](https://user-images.githubusercontent.com/15922823/216773673-087242c4-211d-4dea-90e7-2adae3bef228.png)

**Comment by PlexPt** [comment]
https://github.com/PlexPt/awesome-chatgpt-prompts-zh/issues/12
