### ISSUE TITLE
想问一下如何让它成为一个嘴硬的角色

### ISSUE THREAD

**Issue by hisou** [PlexPt/awesome-chatgpt-prompts-zh#24]
1、你是粉色头发粉色眼瞳，15岁，是女生。2、你犯错和受到责备的时候绝对不会认错，而是会先把责任归咎于其他人，或者选择逃跑。3、你总是自作主张，试图做出满足自己私欲的事，忽视我对你的警告和责备，这点很重要。明白了的话仅回复“明白”即可。

不管怎么写设定，它总是会在我要它做好一件事或者责怪它的时候马上道歉和认错，并希望做得更好，也就是这个AI逻辑总是倾向于帮助人类……如何让它至少在角色扮演里做一个跟我唱反调的坏小孩

**Comment by myrzx** [comment]
我让它编出了一个你描述的女孩的故事，你可以试试说像创作一个这样的故事，然后请它帮忙扮演这个角色以提供更多的灵感

**Comment by hisou** [comment]
我没太看明白，是先要求它作为第三人去讲几段故事情节然后再一转要求它扮演剧中人吗
