### ISSUE TITLE
似乎大部分案例直接翻译自awesome-chatgpt-prompts这个项目，应该说明来源？

### ISSUE THREAD

**Issue by Xander23333** [PlexPt/awesome-chatgpt-prompts-zh#32]
如题。我认为在readme中注明测试案例的来源很重要，并非所有的测试案例都是由作者亲自测试的，因此应该尊重其他开源项目的努力。何况加群还要赞赏作者1元以上，应该让大家知道赞赏的工作是哪些部分吧，只是机器翻译一下值得赞赏吗？以及有不少prompts是不能用的，我很怀疑是否实际用中文和chat-gpt测试过，还是只是翻译个文档挂在这里恰烂钱？

原项目链接：https://github.com/f/awesome-chatgpt-prompts

**Comment by ByYogi** [comment]
谢谢你，真相侠

**Comment by PlexPt** [comment]
说明了的

**Comment by Xander23333** [comment]
> 说明了的

在哪里说明了呢？

**Comment by Xander23333** [comment]
我想知道除了机器翻译和引流恰饭之外这个仓库还做了什么工作？

**Comment by PlexPt** [comment]
实际上之前主要内容比较敏感，后来删去了大部分吧，所以现在看起来readme内容不多

**Comment by PlexPt** [comment]
https://github.com/PlexPt/awesome-chatgpt-prompts-zh/blob/main/USEAGE.md

**Comment by PlexPt** [comment]
你是没见到真正恰饭的人，跟传销一样

**Comment by GrayXu** [comment]
确实基本是一样的。翻了下最前面的commit，这个repo就是从机翻演变来的。翻译工作倒也是工作，但虽然原repo是CC0协议，这里把所有prompts的署名都去除，只在readme末尾保留一个#感谢，还是有点无法评价。。
