### ISSUE TITLE
加微信群还要收费一元起？

### ISSUE THREAD

**Issue by renqiang06** [PlexPt/awesome-chatgpt-prompts-zh#41]
可能是我白嫖惯了吧，哎。人家可以Tg，discord直接进讨论组，进微信群收费我还是觉得功利心太重了

**Comment by PlexPt** [comment]
微信群需要手动拉，一个人得几十秒，遇到名字不常见的更长。纯体力活

**Comment by zsnjuts** [comment]
主要是微信群里根本没有价值内容，每天一条消息都没，智商税，别进
