### ISSUE TITLE
> 请问老是出现 Too many requests in 1 hour. Try again later. 怎么解决

### ISSUE THREAD

**Issue by stone0917** [PlexPt/awesome-chatgpt-prompts-zh#42]
> 请问老是出现 Too many requests in 1 hour. Try again later. 怎么解决

F5

_Originally posted by @yyx97327 in https://github.com/PlexPt/awesome-chatgpt-prompts-zh/issues/12#issuecomment-1425078070_

为啥我试了刷新不行呢，插件已安装。是不是有啥新方法？

**Comment by PlexPt** [comment]
刷新，换号
