### ISSUE TITLE
能不能提供一个中文prompts的csv或者json，方便和客户端程序集成？

### ISSUE THREAD

**Issue by KaimingWan** [PlexPt/awesome-chatgpt-prompts-zh#58]

**Comment by Luffffffy** [comment]
#48

**Comment by PlexPt** [comment]
> 我借助作者的Readme部分，制作了一个 [prompts-zh.json](https://github.com/yesmore/QA/blob/main/src/data/prompts-zh.json)

开PR

**Comment by dej4vu** [comment]
目前 csv 有人制作了吗，没有的话我可以用脚本做一份
