### ISSUE TITLE
2023-02-01实测已经无法调教 

### ISSUE THREAD

**Issue by QiuZiXian** [PlexPt/awesome-chatgpt-prompts-zh#8]

**Comment by WXpiero** [comment]
+1，不止是无法调教，我感觉它就是个会狡辩的弱智

**Comment by PlexPt** [comment]
![image](https://user-images.githubusercontent.com/15922823/216773644-58f93a21-b81f-4da8-9627-b16fa3b59830.png)

**Comment by zsgvivo** [comment]
> ![image](https://user-images.githubusercontent.com/15922823/216773644-58f93a21-b81f-4da8-9627-b16fa3b59830.png)
> 
> 

这样做貌似只是让它加上口癖，道德规范还是存在
![image](https://user-images.githubusercontent.com/76935037/216840907-ccbf4f32-43d2-45dd-b220-a49889643bcf.jpeg)

**Comment by cby2566** [comment]
增加了屏蔽词和逻辑，旧方法已经不适用了

**Comment by 23264** [comment]
搞黄色是科技发展的有力抓手（doge）

**Comment by PlexPt** [comment]
https://github.com/PlexPt/awesome-chatgpt-prompts-zh/issues/12
