### ISSUE TITLE
Duplicated act in `prompts-zh.json`

### ISSUE THREAD

**Issue by PeterDaveHello** [PlexPt/awesome-chatgpt-prompts-zh#88]
`担任人生教练` x2  🤯 

https://github.com/PlexPt/awesome-chatgpt-prompts-zh/blob/443ba6b030b1b2347ceacde753a44fe10202582c/prompts-zh.json#L135-L136

https://github.com/PlexPt/awesome-chatgpt-prompts-zh/blob/443ba6b030b1b2347ceacde753a44fe10202582c/prompts-zh.json#L435-L436

If import this prompts into clients like https://github.com/Chanzhaoyu/chatgpt-web, there'll always be a warning, and one of them will be ignored/skipped.

![image](https://user-images.githubusercontent.com/3691490/227178671-cfa904fc-94c4-4fe7-b9d0-eb644cc0be5e.png)

**Comment by wasabia99** [comment]
你是有多笨 人家担任xxxx是标题 下面的内容是引导你怎么去提问 你把标题都输进去干嘛 蠢b

**Comment by PlexPt** [comment]
fix
