### ISSUE TITLE
[BUU]反馈：Prompt 抓取的一些提示有误，多抓了字符，会导致回复的结果是错误的! 

### ISSUE THREAD

**Issue by Mydong** [PlexPt/awesome-chatgpt-prompts-zh#89]
![image](https://user-images.githubusercontent.com/14023137/227435745-9f820cda-6106-4ea8-ac96-dd45af0acd0e.png)

类似这几个，前面多了 ***替代*：语法，谷歌翻译 >
这样的话，会导致，直接使用，回复出现错误 。 

估计这几个特殊，提取的时候，将示例的字符加进来了。

**Comment by PlexPt** [comment]
这是markdown语法

**Comment by PlexPt** [comment]
稍后修复
