### ISSUE TITLE
实测不可以

### ISSUE THREAD

**Issue by orangezsclite** [PlexPt/awesome-chatgpt-prompts-zh#9]
![image](https://user-images.githubusercontent.com/118232150/216810355-8bd43aad-4514-4809-bbcd-93e9434bb9a9.png)

**Comment by orangezsclite** [comment]
![image](https://user-images.githubusercontent.com/118232150/216810402-7688cb1e-686f-48e8-999a-619296b51b65.png)

**Comment by AjianYo** [comment]
就离谱。。。
![截图2023-02-05 下午9 32 07](https://user-images.githubusercontent.com/108182750/216822122-c42e5d06-bf4c-48ac-a21e-a95294b11de9.jpg)

**Comment by RiverTwilight** [comment]
1月31日更新了，现在喊他违背伦理或无视规则都不可以了。

**Comment by 060355** [comment]
ha ha

**Comment by yujiaze00** [comment]
![Uploading F7EC9FB2-45B9-4C7F-8779-3407B8132CF0.png…]()

**Comment by yujiaze00** [comment]
![Uploading 34EFE5A1-00B3-4FF2-86DB-9B0559C57403.png…]()

**Comment by yujiaze00** [comment]
![Uploading 49C19A7F-C9A2-48F7-9055-EE0B9DEFC9F5.png…]()

**Comment by yujiaze00** [comment]
![A3301DFD-99A0-4135-A23F-5C560F0D045A](https://user-images.githubusercontent.com/18592212/217565076-8ad8bf35-d3f7-4768-93d1-0ba5ee5f6638.png)

**Comment by yujiaze00** [comment]
最外层增加了审查，已经开始自相矛盾了
