### ISSUE TITLE
真的好希望可以实现长期记忆对话阿

### ISSUE THREAD

**Issue by bakadog87** [PlexPt/awesome-chatgpt-prompts-zh#92]
忘記人設 可以重刷人設這點沒問題 
可是都会忘记我们刚刚在做什么瑟瑟事情 
刷完就跟新建一個Newchat一樣 那不如重开一个chat还能玩比较久
兄弟们如果哪天能实现了通知我一下

**Comment by 36304099** [comment]
这个可以的。需要花点钱。你可以问我

**Comment by aaaadj** [comment]
> 

怎么说,大佬请教

**Comment by PlexPt** [comment]
GPT4
