### ISSUE TITLE
GPT提示词

### ISSUE THREAD

**Issue by qd2000** [PlexPt/awesome-chatgpt-prompts-zh#94]

**Comment by jackerman8026** [comment]
Dear [sender],

Thank you for getting in touch and for keeping me updated on the project. I
appreciate your efforts in subscribing me to this thread so I won't miss
any important updates.

Best regards,
[Your name]


Written with Compose.ai
<https://www.compose.ai/?utm_campaign=referral&utm_medium=signature&utm_source=e25e2db2-ff8b-4090-9a41-ca63490ae527>

邱冬 ***@***.***> 于2023年3月26日周日 12:32写道：
